language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
script:
  - pytest
deploy:
  provider: pypi
  user: slipknothoudini
  password:
    secure: uEw9Mboi2jTDD2SWqrTNbkNQioA/je8bmPHXkhXrF5P59jTlgmuNrhieIymjv6hbhSLTmRzbz8Dta/w6mHhzkp3KWYMh12zupuj44Kyp+oOI771VkfaLVEXV1cfWn4d4PJV03sZYM8Kb/X2/6e6s0QCsL0S2euesSKZ04O473BdaptRU7fJkvY6AKDHVDZvFsUdhv57y1itqDFZ25g1j6KN8dtAvGzaHvK4rsZRRg2ZDaHYGA7hme7AryZw2QsNqS9UGiEJJ/ao2DWInCx1KviDIxAQOJNs7rW8CurnGvQysv7IemFNARPgl3ubCz++cJuvgj1golgUCn6zWFvnY99kpx1rG7CFIEjqvjJtxIXUxKnhCFY4zGk4guT17okkOhfmqAvlmSkht4xFg2ss4D33LSmNJrbZQ/unoLGh4Xx6cVDhu+ViF/mep3SIHNIPSgaSJoZmLw7uqMpS1wjZZvl0SrtEmW9GbZvbUwdy8AwlXN1qBdc+O2P21dXYBnCNJGg0l5RD8g/L8cVnTmcblsqY/GJf0ICZ94G9Lk10bi+wk9e/uhRrL11x9vToGETtYyTfWoP4i7TFWIREmGuok8dYSSmKokBK3WLN7T9QB/GfhNOgck3p2wAUUYTxv3GG2ImWuzdo7T+871H3GM5l9MkWniqzK04aiVCXHo7Wir9E=
  on:
    branch: master