name: Daily Develop Build

# Controls when the action will run (on cron schedule)
on:
  schedule:
  # everyday at noon
  - cron: "0 12 * * *"

jobs:

  # build our project
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9']

    name: Run with ${{ matrix.python-version }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: develop

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt
          pip install pytest

      - name: run pytest
        run: pytest
